system:
  certificateFilePath: "parsec:"
  #privateKeyPath: "${GGC_ROOT_PATH}/private.pem.key"
  # the object in the URI is the actual label given the private key
  privateKeyPath: "parsec:"
  rootCaPath: "${GGC_ROOT_PATH}/AmazonRootCA1.pem"
  rootpath: ""
  thingName: "${THING_NAME}"
services:
  aws.greengrass.Nucleus:
    componentType: "NUCLEUS"
    version: "2.5.0"
    configuration:
      awsRegion: "eu-central-1"
      iotRoleAlias: "GreengrassCoreTokenExchangeRoleAlias"
      iotDataEndpoint: "device-data-prefix-ats.iot.eu-central-1.amazonaws.com"
      iotCredEndpoint: "device-credentials-prefix.credentials.iot.eu-central-1.amazonaws.com"
  aws.greengrass.crypto.Pkcs11Provider:
    configuration:
      # requied, but value doesn't matter, labelling the backend of the provider
      pemCaPath: ...
      pemCertPath: ...
      importKeyPath: ...
      parsecKeyName: ...
      parsecAppName: ...
      name: softhsm2
      library: /usr/lib/softhsm/libsofthsm2.so
      slot: $SLOT
      userPin: 1234