[core_settings]
log_timestamp = true
log_error_details = true
allow_root = true

[listener]
listener_type = "DomainSocket"
timeout = 200 # in milliseconds
socket_path = "/run/parsec/parsec.sock"

[authenticator]
auth_type = "UnixPeerCredentials"
admins = [ { name = "root" }, { name = "parsec" } ]

[[key_manager]]
name = "on-disk-manager"
manager_type = "OnDisk"
store_path = "/var/lib/parsec/mappings"

[[provider]]
provider_type = "MbedCrypto"
key_info_manager = "on-disk-manager"
